### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by neu-ma-tic**
thank you discord for breaking literally all code made for you <3

(#7)

### CODE REVIEW

**Comment by neu-ma-tic** [comment]
this adds the axios package and fixes what i wrote out in #7

**Comment by Vap0r1ze** [comment]
> thank you discord for breaking literally all code made for you <3

literally this
gonna check out this pr right now

**Comment by Vap0r1ze** [comment]
yea seems fine to me thank u

**Comment by neu-ma-tic** [comment]
ok 👌

**Pull request merged**
